### ISSUE TITLE
postgresql init issue after upgrade

### ISSUE THREAD

**Issue by sniper7kills** [zammad/zammad-helm#191]
**What happened**: When attempting to upgrade to the latest helm chart and Zammad 6.0.0-32 I received the following error on the postgresql-init container:

```
I, [2023-06-23T13:48:54.432823#8-6180]  INFO -- : Using memcached as Rails cache store.
I, [2023-06-23T13:48:54.432999#8-6180]  INFO -- : Using the Redis back end for Zammad's web socket session store.
I, [2023-06-23T13:48:55.023446#8-6180]  INFO -- : Setting.set('product_logo', "79c1feb0116e657e2a1b58841ff31cf1.png")
rake aborted!
Errno::EROFS: Read-only file system @ rb_sysopen - /opt/zammad/public/assets/images/79c1feb0116e657e2a1b58841ff31cf1.png
/opt/zammad/lib/static_assets.rb:177:in `initialize'
/opt/zammad/lib/static_assets.rb:177:in `open'
/opt/zammad/lib/static_assets.rb:177:in `sync'
/opt/zammad/config/initializers/logo.rb:11:in `block in <main>'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:603:in `catch'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `each'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:88:in `prepare!'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:391:in `initialize!'
/opt/zammad/config/environment.rb:7:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**What you expected to happen**:
With the new layout I wouldn't expect to have the `bundle exec rake db:migrate` command writing to any directory outside of `/opt/zammad/var`

**Comment by greedybro** [comment]
Hello !

I have the same error trying to upgrade to chart 9.0.2 from 8.2.2

**Comment by monotek** [comment]
Does it work if you add "--set zammadConfig.initContainers.postgresql.securityContext.readOnlyRootFilesystem=false" to your helm upgrade command or set in your values file?

**Comment by greedybro** [comment]
No change with the `readOnlyRootFilesystem=false` in values, still the same error.

Note that I now have to set the following in the value or the `data-chmod` container fails with a "permission denied". Not sure it's related, but since most of the change in the chart are volume related...

```
securityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
 ```

**Comment by sniper7kills** [comment]
> Does it work if you add "--set zammadConfig.initContainers.postgresql.securityContext.readOnlyRootFilesystem=false" to your helm upgrade command or set in your values.yaml file?

Yes; that allows the postgresql-init container to finish starting. Thank you!

**Comment by monotek** [comment]
maybe adding the fix from https://github.com/zammad/zammad/pull/4684 would help.
hopefully i can find some time the next days to test it.

**Comment by alexkorotysh** [comment]
Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/zammad/storage/fs/3bc5/897d/001f9/61170/e3344f4/877996c/8854fe4f3194c99a9943f8b7c7f380a0
getting this error, just a nightmare, cause changed directory

**Comment by monotek** [comment]
I've created an pr which hopefully workarouds the issue: https://github.com/zammad/zammad-helm/pull/197

You might test it via my branch: https://github.com/monotek/zammad-helm/tree/storage

**Comment by rmuehlbauer** [comment]
for me to finally get it working again - even after https://github.com/zammad/zammad-helm/pull/197 - I had to manually make some additional changes:

changes to the **postgresql** and **elasticsearch** init containers:
- also "dual-mount" the fs under _/opt/zammad/var_ AND _/opt/zammad/storage_ here
- set `readOnlyRootFilesystem: false`

for the **zammad-railsserver**,  **zammad-scheduler** and **zammad-websocket** container I had to set
- `readOnlyRootFilesystem: false`
to prevent getting some kind of "Read-only file system" errors in all the mentioned containers


And there is still one thing I cant get to work - the logo on the login page ist gone. Even if I set a new logo, it wont show again...weird.

**Comment by bo0ts** [comment]
@monotek I second that. Even with the #197 the upgrade failed.

**Comment by monotek** [comment]
Possible fix in: https://github.com/zammad/zammad-helm/pull/206
