### ISSUE TITLE
Unable to upgrade 8.3.1 -> 9.0.0

### ISSUE THREAD

**Issue by Sacerdoss** [zammad/zammad-helm#195]
**Version of Helm and Kubernetes**:
Kubernetes Version: 1.25.10
Helm Version: 3.8.2

**What happened**:
I followed described steps to upgrade zammad from 8.3.1 to 9.x.x
1. `kubectl delete sts zammad`
2. `helm upgrade `

The new Statefulset was created, the init container zammad-init finished successfully but postgresql-init did not with the following error:
```log
kubectl -n zammad logs -f zammad-0 -c postgresql-init
I, [2023-06-28T11:19:19.077560 #11]  INFO -- : ActionCable is using the redis instance at redis://:zammad@zammad-redis-master:6379.
I, [2023-06-28T11:19:19.157126#11-6180]  INFO -- : Using memcached as Rails cache store.
I, [2023-06-28T11:19:19.157472#11-6180]  INFO -- : Using the Redis back end for Zammad's web socket session store.
I, [2023-06-28T11:19:20.054648#11-6180]  INFO -- : Setting.set('product_logo', "e8f0cb0c24120a12e01bf9a07824ebb4.png")
rake aborted!
Errno::EROFS: Read-only file system @ rb_sysopen - /opt/zammad/public/assets/images/e8f0cb0c24120a12e01bf9a07824ebb4.png
/opt/zammad/lib/static_assets.rb:177:in `initialize'
/opt/zammad/lib/static_assets.rb:177:in `open'
/opt/zammad/lib/static_assets.rb:177:in `sync'
/opt/zammad/config/initializers/logo.rb:11:in `block in <main>'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:603:in `catch'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `each'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:88:in `prepare!'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:391:in `initialize!'
/opt/zammad/config/environment.rb:7:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.7.3/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

I suspect some issues with our current zammad configuration not working well with the change of the pvc. Do I need to manually copy data from the old pvc to the new one?

**What you expected to happen**:

Zammad upgrade to go through.

**Comment by Sacerdoss** [comment]
Seems like the issue comes from `Settings -> Branding -> Logo` which places the chosen image file into `zammad/public/assets/images` in 8.3.1.
I suspect the upgrade would work if i removed the logo from our settings. I will try to find out how to do that since the UI does only allow changing it for another one and try that.

**Comment by monotek** [comment]
see also: https://github.com/zammad/zammad-helm/issues/194
