### ISSUE TITLE
customInit: Can't find config setting 

### ISSUE THREAD

**Issue by klml** [zammad/zammad-helm#234]
**Version of Helm and Kubernetes**:

* Kustomize Version: v4.5.4
* Kubernetes Version: v1.26.9+07c0911
* zammad-10.1.0

**What happened**:
Using the new customInit from #231

```
zammadConfig:
  initContainers:
    zammad:
      customInit: bundle exec rails r "Setting.set(\"user_email_multiple_use\", \"true\")"
```

leads to a correct ConfigMao
```

$ oc get cm zammad-init -o yaml | grep email -B2
        echo "${AUTOWIZARD_JSON}" | base64 -d > /opt/zammad/var/auto_wizard.json
    fi
    bundle exec rails r "Setting.set(\"user_email_multiple_use\", \"true\")"
```

but fails in zammad-init with `Can't find config setting`.
```
$ oc logs zammad-1 -c zammad-init -f
I, [2023-11-21T12:55:52.258560 #7]  INFO -- : ActionCable is using the redis instance at redis://:zammad@zammad-redis-master:6379.
I, [2023-11-21T12:55:52.284601#7-5520]  INFO -- : Using memcached as Rails cache store.
I, [2023-11-21T12:55:52.284888#7-5520]  INFO -- : Using the Redis back end for Zammad's web socket session store.
/opt/zammad/app/models/setting.rb:38:in `set': Can't find config setting 'user_email_multiple_use' (RuntimeError)
        from /usr/local/bundle/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/bundle/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/bundle/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
```

**What you expected to happen**:

same as with exec
```
$ oc exec zammad-0 -c zammad-railsserver -- rails r 'p Setting.set("user_email_multiple_use", true)'
I, [2023-11-21T13:00:12.062167 #24]  INFO -- : ActionCable is using the redis instance at redis://:zammad@zammad-redis-master:6379.
I, [2023-11-21T13:00:12.114569#24-5520]  INFO -- : Using memcached as Rails cache store.
I, [2023-11-21T13:00:12.114948#24-5520]  INFO -- : Using the Redis back end for Zammad's web socket session store.
I, [2023-11-21T13:00:18.794269#24-5520]  INFO -- : Setting.set('user_email_multiple_use', true)
true
```

**Comment by mgruner** [comment]
@klml can you try again with the latest version, please?

**Comment by klml** [comment]
@mgruner works perfect. Thank you very much. 🥳
