### ISSUE TITLE
`helm test` fails with exception

### ISSUE THREAD

**Issue by mueller-ma** [zammad/zammad-helm#290]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

````
$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
zammad          zammad-test     20              2024-08-15 06:25:20.558452295 +0000 UTC         deployed        zammad-12.3.0           6.3.1-91
$ helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}
````

**What happened**:

````
$ helm test zammad
NAME: zammad
LAST DEPLOYED: Thu Aug 15 06:25:20 2024
NAMESPACE: zammad-test
STATUS: deployed
REVISION: 20
TEST SUITE:     zammad-run-tests
Last Started:   Thu Aug 29 13:27:25 2024
Last Completed: Thu Aug 29 13:27:39 2024
Phase:          Failed
NOTES:
1. Get the application URL by running these commands:
  <redacted>
Error: 1 error occurred:
        * pod zammad-run-tests failed
$ kubectl logs zammad-run-tests
rake aborted!
Don't know how to build task 'zammad:helm:test' (See the list of available tasks with `rake --tasks`)
Did you mean?  zammad:db:reset
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
````

**What you expected to happen**:

I expect the test to pass. If there's an issue with the Zammad installation, provide a more helpful error message in the log.

**How to reproduce it** (as minimally and precisely as possible):

````
$ helm install zammad zammad/zammad  # Official repo
$ helm test zammad
````

**Comment by mgruner** [comment]
This is used in our CI and requires `zammad/ci/full-objects.yaml` and `zammad/ci/default-values.yaml` to be used. It adds a command to Zammad via custom mountpoint, which then gets executed by Zammad.

**Comment by mgruner** [comment]
See also [.github/workflows/ci.yaml](.github/workflows/ci.yaml).

**Comment by mueller-ma** [comment]
I'm not sure if I understand when and who may execute `helm test`, but to me it seems that it should also succeed on every deployment.

> For a chart consumer, this is a great way to check that their release of a chart (or application) works as expected.

from https://helm.sh/docs/topics/chart_tests/


Here's an example of a test case for mysql that is altered based on the enabled variables: https://github.com/helm/charts/blob/master/stable/mysql/templates/tests/test-configmap.yaml

**Comment by mgruner** [comment]
@mueller-ma thanks a lot for your explanation. Can you please see if #292 will address your concern properly?

**Comment by mueller-ma** [comment]
On a test deployment the three test suites pass now 👍
