### ISSUE TITLE
migrations don't run

### ISSUE THREAD

**Issue by carstenblt** [zammad/zammad-helm#302]
With the latest chart, startup fails because the migrations don't run. Trying to manually run them fails like this:

```
zammad@zammad-nginx-6548889d58-7t8cg:~$ bin/rails db:migrate --trace RAILS_ENV=production
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
bin/rails aborted!
ActiveRecord::PendingMigrationError:  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=production

You have 22 pending migrations:

db/migrate/20240509100920_permission_switch_to_label_description.rb
db/migrate/20240607144905_ensure_no_commas_and_asterisks_in_tag_names.rb
db/migrate/20240618074549_drop_templates_groups_table.rb
db/migrate/20240618081710_migrate_template_options.rb
db/migrate/20240716075304_issue5147_modified_operator.rb
db/migrate/20240718192329_rename_ticket_overview_priority_icon_setting.rb
db/migrate/20240729100324_add_checklists.rb
db/migrate/20240802143314_add_setting_option_for_postmaster_follow_up_search_in.rb
db/migrate/20240809070038_remove_active_checklist.rb
db/migrate/20240812111200_add_checklist_item_ticket_association.rb
db/migrate/20240819100430_auth_third_party_no_create_user.rb
db/migrate/20240821053112_drop_ticket_flags_table.rb
db/migrate/20240906090321_drop_unused_article_references.rb
db/migrate/20240906135440_add_more_missing_permissions.rb
db/migrate/20240909062109_add_service_name_to_active_storage_blobs.active_storage.rb
db/migrate/20240909062110_create_active_storage_variant_records.active_storage.rb
db/migrate/20240909062111_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
db/migrate/20240930184012_checklist_improve_reference_tracking.rb
db/migrate/20241001062820_synchronize_checklist_item_state_from_tickets.rb
db/migrate/20241021191549_move_checklist_ticket_relation_to_ticket.rb
db/migrate/20241028081431_issue5381_fix_description.rb
db/migrate/20241104151855_issue5390_taskbar_remove_duplicated_key_by_user.rb


/usr/local/bundle/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:692:in `check_pending!'
/opt/zammad/config/initializers/active_record_pending_migrations.rb:4:in `<main>'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:690:in `load'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:690:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-7.1.4.1/lib/active_support/notifications.rb:208:in `instrument'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:689:in `load_config_initializer'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:643:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:642:in `each'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/engine.rb:642:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/application.rb:426:in `initialize!'
/opt/zammad/config/environment.rb:7:in `<main>'
/usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/application.rb:402:in `require_environment!'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/application.rb:591:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:241:in `each'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:241:in `each'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/command.rb:156:in `invoke_rake'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/command.rb:73:in `block in invoke'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/command.rb:149:in `with_argv'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/command.rb:69:in `invoke'
/usr/local/bundle/gems/railties-7.1.4.1/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

**Comment by monotek** [comment]
Have you done the major postgres update described in the release notes?

https://github.com/zammad/zammad-helm/releases/tag/zammad-13.0.0

**Comment by carstenblt** [comment]
@monotek I am using an external Postgres 16 instance. Does 6.4 require postgres 17?

**Comment by monotek** [comment]
no

**Comment by mgruner** [comment]
@carstenblt all deployments set a variable `RAILS_CHECK_PENDING_MIGRATIONS: 'true'`, which causes this behaviour. There is a `Job` in the chart which is started on all updates, which does not have this set. This job is responsible to execute the migrations, and the other PODs keep restarting until that process finished.

Can you check the job logs and post them here, please? As a workaround you can also unset the variable mentioned above to execute the rails migrations in another container manually.

**Comment by carstenblt** [comment]
@mgruner I see. The init job is already gone but migrations fail - that's probably what happened in the init job too.

```
I, [2024-11-13T07:58:06.725923#164-7000]  INFO -- : Migrating to RemoveActiveChecklist (20240809070038)
== 20240809070038 RemoveActiveChecklist: migrating ============================
-- remove_column(:checklists, :active)
   -> 0.0026s
== 20240809070038 RemoveActiveChecklist: migrated (0.0130s) ===================

WARNING:  you don't own a lock of type ExclusiveLock
bin/rails aborted!
ActiveRecord::ConcurrentMigrationError:  (ActiveRecord::ConcurrentMigrationError)

Failed to release advisory lock



Caused by:
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block


Caused by:
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (ActiveRecord::StatementInvalid)


Caused by:
PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (PG::InFailedSqlTransaction)

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

This one I was able to work around by killing the old pod and quickly running the migration. Now stuck with another fail:

```
== 20241021191549 MoveChecklistTicketRelationToTicket: migrating ==============
-- change_table(:tickets)
   -> 0.0143s
-- remove_reference(:checklists, :ticket)
   -> 0.0023s
== 20241021191549 MoveChecklistTicketRelationToTicket: migrated (0.0377s) =====

bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block


Caused by:
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (ActiveRecord::StatementInvalid)


Caused by:
PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (PG::InFailedSqlTransaction)

Tasks: TOP => db:migrate
```

**Comment by mgruner** [comment]
This sounds like database issues, not Zammad.

**Comment by carstenblt** [comment]
Well, it's pretty impossible to debug. The DB itself is fine, it's a managed Postgres server, that also serves a few other DBs.

**Comment by carstenblt** [comment]
Mh I see...

```
[27-1] pid=531288,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] ERROR: prepared statement "a1" does not exist
[27-2] pid=531288,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] STATEMENT: DEALLOCATE a1
[25-1] pid=531310,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] ERROR: prepared statement "a2" does not exist
[25-2] pid=531310,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] STATEMENT: DEALLOCATE a2
[58-2] pid=523127,user=zammad,db=zammad,app=bin/rails,client=[local] STATEMENT: DEALLOCATE a1
```

**Comment by carstenblt** [comment]
Fixed by changing the postgres connection pool from transactional to session - though I really would not have expected that this is needed.

**Comment by mgruner** [comment]
Thanks for the update.
